// app/layout.tsx
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";

import { ModalProvider } from "./context/ModalContext"; 
import { AuthProvider } from "./context/AuthContext";   
import AuthModal from "@/pages/AuthModal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}>
        <AuthProvider> {/* 🛡️ Wrap the whole app in AuthProvider FIRST */}
          <ModalProvider> {/* ModalProvider goes INSIDE AuthProvider */}
            <Navbar />
            <main className="flex-grow">{children}</main>
            <AuthModal />
          </ModalProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
